/** Maps a slugified raw token to a canonical blip name.
 *  Seeded from common ecosystem packages; extend as detection coverage grows. */
export const ALIASES: Record<string, string> = {
  react: 'React',
  'react-dom': 'React',
  next: 'Next.js',
  nextjs: 'Next.js',
  vue: 'Vue.js',
  express: 'Express',
  fastapi: 'FastAPI',
  django: 'Django',
  flask: 'Flask',
  boto3: 'AWS',
  'aws-sdk': 'AWS',
  spring: 'Spring',
  'spring-boot': 'Spring',
  laravel: 'Laravel',
  symfony: 'Symfony',
  typescript: 'TypeScript',
  go: 'Go',
  golang: 'Go',
  python: 'Python',
  java: 'Java',
  php: 'PHP',
  vite: 'Vite',
  vitest: 'Vitest',
  playwright: 'Playwright',
  prisma: 'Prisma',
  redis: 'Redis',
  postgresql: 'PostgreSQL',
  postgres: 'PostgreSQL',
  docker: 'Docker',
  terraform: 'Terraform',
  kubernetes: 'Kubernetes',
  'github-actions': 'GitHub Actions',
  // promoted from candidates after the first real scan (high adoption across repos)
  angular: 'Angular',
  nestjs: 'NestJS',
  tailwindcss: 'Tailwind CSS',
  eslint: 'ESLint',
  prettier: 'Prettier',
  jest: 'Jest',
  rxjs: 'RxJS',
  zod: 'Zod',
}
